---
# Remove all configuration AND DATA from the containerhost

- name: Reset containerhost and ERASE ALL DATA
  ansible.builtin.shell:
    cmd: |
      podman rm --force --all
      podman rmi --force --all
      podman pod rm -af
      rm -rf /home/{{ ansible_user }}/container-projects
      rm -rf /home/{{ ansible_user }}/.config
      rm -rf /home/{{ ansible_user }}/.local
      sudo rm -rf /etc/systemd/user/podman-compose@.service

  args:
    chdir: .
    creates: /tmp/run-this-task-unconditionally